name: Flutter APK Builder

on:
  workflow_dispatch:
    inputs:
      zip_url:
        description: 'URL ZIP project Flutter'
        required: true
      tag:
        description: 'Tag build'
        required: true
      build_type:
        description: 'debug atau release'
        default: 'release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Download ZIP
        run: wget -O project.zip "${{ github.event.inputs.zip_url }}"

      - name: Unzip
        run: unzip project.zip -d project/

      - name: Build APK
        run: |
          cd project
          flutter pub get
          if [ "${{ github.event.inputs.build_type }}" == "debug" ]; then
            flutter build apk --debug
          else
            flutter build apk --release --no-tree-shake-icons
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-build
          path: project/build/app/outputs/flutter-apk/*.apk
